config/routes.rb
Rails.application.routes.draw do
  root 'departments#index'

  resources :departments  do
	resources :items
	end

  resources :items do
    resources :comments
  	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_item
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = @item.comments
  end

  def show
  end

  def new
    @comment = @item.comments.new
  end

  def create
    @comment = @item.comments.new(comment_params)
    if @comment.save
      redirect_to item_comment_path(@item, @comment)
    else
      render :new
    end
  end

  def edit
    render :new
  end

  def update
    if @comment.update(comment_params)
      redirect_to item_comment_path(@item, @comment)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to root_path
  end

  private
  def comment_params
    params.require(:comment).permit(:title, :body, :rating, :author)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search]
      @department = Department.where('name ILIKE ?', "%#{params[:search]}%")
    else
      @department = Department.all
    end
  end

  def show
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to @department
    else
      render :new
    end
  end

  def edit
    render :new
  end

  def update
    if @department.update(department_params)
      redirect_to @department
    else
      render :new
    end
  end

  def destroy
    @department.destroy
    redirect_to root_path
  end

  private
  def department_params
    params.require(:department).permit(:search, :name, :image_link)
  end

  def set_department
    @department = Department.find(params[:id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = @department.items
  end

  def show
  end

  def new
    @item = @department.items.new
  end

  def create
    @item = @department.items.new(item_params)
    if @item.save
      redirect_to department_item_path(@department, @item)
    else
      render :new
    end
  end

  def edit
    render :new
  end

  def update
    if @item.update(item_params)
      redirect_to department_item_path(@department, @item)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  private
  def item_params
    params.require(:item).permit(:name, :price, :description, :image_link)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_department
    @department = Department.find(params[:department_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/comments/index.html.erb
<h2><%= @comments.length <= 0 ? "Write the first comment!" : "" %></h2> 

  <% @comments.each do |comment| %>
      <h1><%= link_to comment.title, comment %></h1>
      <p>Title: <%= comment.title %></p>
      <p>Review: <%= comment.body %></p>
  <% end %>

<%= link_to 'New Comment', new_item_comment_path(@item) %>

app/views/comments/new.html.erb
<h1>Comments Submission</h1>

<%= form_for [@item, @comment] do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, required: true, class: 'form-control' %>
    <br>
    <%= f.label :body %>
    <%= f.text_area :body, required: true, class: 'form-control' %>
    <br>
    <%= f.label 'Rating:' %>
    <%# f.select :rating, [['⭐⭐⭐⭐⭐',1], ['⭐⭐⭐⭐',2], ['⭐⭐⭐',3], ['⭐⭐',4], ['⭐',5]], required: true, class: 'form-control'%>
    <%= f.select :rating, ['⭐⭐⭐⭐⭐', '⭐⭐⭐⭐', '⭐⭐⭐', '⭐⭐', '⭐'], class: 'form-control'%>
    <br>
    <%= f.label :author %>
    <%= f.text_field :author, required: true, class: 'form-control' %>
    <br>
    <br>
    <%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<h1>Comment Details</h1>

<h2>Rating: <%= @comment.rating %></h2>
<p>Title: <%= @comment.title %></p>
<p>Review: <%= @comment.body %></p>
<p>Written By: <%= @comment.author %></p>

<div class="controls mt-3 mb-3">
<%= link_to 'Back', department_path %> |
<%= link_to 'Edit Comment', edit_item_comment_path(@item) %> |
<%= link_to 'Delete', [@item, @comment], method: :delete %> |
</div>

app/views/departments/index.html.erb
<nav class="navbar navbar-expand navbar-light bg-light">

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% @department.each do |department| %>
          <%= link_to department.name, department, class: 'dropdown-item' %>
    <% end %>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
    <%= form_tag(departments_path,  method: :get) do %>
  <%= text_field_tag :search, params[:search], placeholder: 'Department',class: 'form-control' %>
  <%= submit_tag 'Search', name: nil, class: 'btn btn-outline-danger my-2 my-sm-0' %> 
<% end %>
    </form>
  </div>
</nav>

<!-- END NAV -->

<!-- CONTENT -->


<div class="row">
<div class="col"></div>
<div class="col-10">

<h1>Welcome to <i class="fas fa-circle"></i> Store</h1>
<h2> <%= @department.length <= 0 ? "Add some departments" : ""  %> </h2>

<% @department.each do |department| %>
    <div class="department-show">
    <div class="department-image" style="background-image: url(<%= department.image_link%>);"> </div>
    <h2> <%= link_to department.name, department %></h2>
    </div>
<% end %>

<div class="mt-3 mb-3">
<button class="btn btn-danger">
<%= link_to 'Add Department', new_department_path %>
</button>
</div>

</div>
<div class="col"></div>
</div>

app/views/departments/new.html.erb
<h1>Department Details</h1>

<%= form_for @department do |f| %>
    <div class="form">
        <div class="form-item mb-3">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-item mb-3">
            <%= f.label :image_link %>
            <%= f.text_field :image_link, class: 'form-control' %>
        </div>
        <div class="form-item mb-3">
            <%= f.submit%>
        </div>
  </div>
<% end %>

<%= link_to 'Back', root_path %>

<hr>
<p>Example image link:: <i>http://bit.ly/2lH7gW4</i> </p>

app/views/departments/show.html.erb
<div class="jumbotron jumboimage" style="background-image: url(<%= @department.image_link%>);">
  <h1 class="display-4"><%= @department.name %></h1>
  <p class="lead">
    New fall collection 
  </p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
</div>

<div class="row">
<div class="col"></div>
<div class="col-10">

<!-- LOOP ALL ITEMS OF DEPARTMENT -->
<div class="department-item-wrapper">
  <% @department.items.each do |item| %>
<div class="department-item-show">
  <div class="department-show-image" style="background-image: url(<%= item.image_link%>);"> </div>
      <h3><%= link_to item.name, [@department, item] %></h3>
      <p>$<%= item.price %></p>
      <button class="btn btn-danger"><%= link_to 'Info', [@department, item] %></button>
</div>
  <% end %>
</div>

<hr>

<div class="controls mt-3 mb-3">
<%= link_to 'Back', root_path %> |
<%= link_to 'Update Department Details', edit_department_path %> |
<%= link_to 'Delete', @department, method: :delete %> |
<%= link_to 'Add Item', new_department_item_path(@department) %> |
</div>

</div>
<div class="col"></div>
</div>

app/views/items/index.html.erb
<h2><%= @items.length <= 0 ? "Add some items" : "" %></h2> 

  <% @items.each do |item| %>
      <h1><%= link_to item.name, [@department, item] %></h1>
      <p>Price: <%= item.price %></p>
      <p>Description: <%= item.description %></p>
  <% end %>

<%= link_to 'New Item', new_department_item_path(@department) %>

app/views/items/new.html.erb
<h1>Item Form</h1>

<%= form_for [@department, @item] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, required: true, class: 'form-control' %>
    <br>
    <%= f.label :price %>
    <%= f.text_field :price, required: true, class: 'form-control' %>
    <br>
    <%= f.label :description %>
    <%= f.text_field :description, required: true, class: 'form-control' %>
    <br>
    <%= f.label :image_link %>
    <%= f.text_field :image_link, required: true, class: 'form-control' %>
    <br>

    <br>
    <%= f.submit %>
<% end %>

<p>Example image link:: <i>http://bit.ly/2mda8KE</i> </p>

app/views/items/show.html.erb
<h1><%= @item.name %> Details</h1>
<hr>
<div class="row">
    <div class="col"></div>
    <div class="col-5">
    <img src="<%= @item.image_link %>" class="image-show">
    </div>
    <div class="col-5">
        <h3><%= @item.name %></h3>
    <h3>Price: $<%= @item.price %></h3>
    <p>Description: <%= @item.description %></p>
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#itemModalCenter">
  Add to cart
</button>
    </div>
    <div class="col"></div>
</div>

<hr>
<h1 class="mt-3 mb-3"><%= @item.name %> Reviews</h1>
<hr>
  <% @item.comments.each do |comment| %>
      <h1><%= link_to comment.title, [@item, comment] %></h1>
      <h3><%= comment.rating %></h3>
      <p>Title: <%= comment.title %></p>
      <p>Review: <%= comment.body %></p>
      <hr>
  <% end %>

<div class="controls mt-3 mb-3">
<%= link_to 'Back', department_path %> |
<%= link_to 'Add Comments', new_item_comment_path(@item) %> |
<%= link_to 'View Comments', item_comments_path(@item) %> |
<%= link_to 'Edit Item', edit_department_item_path(@department) %> |
<%= link_to 'Delete', [@department, @item], method: :delete %> |
</div>

<!-- Modal -->
<div class="modal fade" id="itemModalCenter" tabindex="-1" role="dialog" aria-labelledby="itemModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="itemModalLongTitle">Checkout</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h1><%= @item.name %></h1>
        <p>Has been added to you cart</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Continue Shopping</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg target-nav mb-3">
<%= link_to root_path do %>
<h1><i class="fas fa-circle"></i></h1>
<% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
         <%= link_to 'Departments', root_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
   <%= link_to 'Add Department', new_department_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Target</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
  <script src="https://kit.fontawesome.com/f7bc76f4fa.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <div class="container-fluid">
  <%= render 'layouts/navbar' %>
    <%= yield %>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>